[build-system]
package-mode = false

[project]
name = "files-diniscruz-ai"
version = "v0.3.17"
description = "Dinis Cruz - Files"
readme = "README.md"
authors = [{name = "Dinis Cruz", email = "dinis.cruz@owasp.org"}]
license = {file = "LICENSE"}