name: "s3__sync-folder"
description: "sync local folder to s3"

inputs:
  aws-region:
    required: true
    description: "AWS region for the S3 bucket"
  s3-bucket:
    required: true
    description: "AWS S3 bucket name"
  source_folder:
    required: true
    description: "Local/Source folder to sync with the target folder in S3"
  target_folder:
    required: true
    description: "Target folder to copy the files in S3"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Configure AWS CLI Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy to S3
      shell: bash
      run: aws s3 sync ./${{ inputs.source_folder }}/ s3://${{ inputs.s3-bucket }}/${{ inputs.target_folder }} --delete
