name: CD Pipeline - DEV

on:
  push:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GIT__BRANCH: 'dev'
  RELEASE_TYPE: 'minor'

jobs:
  increment-tag:
    name: Increment Tag - Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}

  publish-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync files folder to S3 Bucket
        uses: ./.github/actions/s3__sync-folder
        with:
          aws-region: "eu-west-2"
          folder    : "./files/"
          s3-bucket : "749670524505--files-diniscruz-ai"
